#!/usr/bin/env python3
"""
build-photo-index.py

Scans images/highlights/ for photos and regenerates
assets/js/photo-index.js, which photography.html reads to pick a
random selection of images for the masonry gallery.

Run this from the site root (the folder this script lives in)
whenever you add, remove, or rename photos in images/highlights/:

    python3 build-photo-index.py

No per-photo metadata is required — a reasonable alt-text caption is
generated automatically from each filename.
"""

import json
import re
import sys
from pathlib import Path

SITE_ROOT = Path(__file__).resolve().parent
PHOTOS_DIR = SITE_ROOT / "images" / "highlights"
OUTPUT_FILE = SITE_ROOT / "assets" / "js" / "photo-index.js"
EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}


def caption_from_filename(name: str) -> str:
    stem = Path(name).stem
    stem = re.sub(r"[_\-]+", " ", stem)
    stem = re.sub(r"\s+", " ", stem).strip()
    if not stem:
        stem = "Untitled photograph"
    return "Photograph by John MacMillan — " + stem


def main():
    if not PHOTOS_DIR.is_dir():
        print(f"No images/highlights/ folder found at {PHOTOS_DIR}", file=sys.stderr)
        sys.exit(1)

    photos = []
    for path in sorted(PHOTOS_DIR.iterdir()):
        if not path.is_file() or path.suffix.lower() not in EXTENSIONS:
            continue
        photos.append({
            "file": f"images/highlights/{path.name}",
            "alt": caption_from_filename(path.name),
        })

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_FILE.open("w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build-photo-index.py — do not edit by hand.\n")
        f.write("// Run `python3 build-photo-index.py` from the site root after adding, removing, or renaming photos.\n")
        f.write("window.SITE_PHOTOS = ")
        json.dump(photos, f, indent=2, ensure_ascii=False)
        f.write(";\n")

    print(f"Wrote {len(photos)} photo(s) to {OUTPUT_FILE.relative_to(SITE_ROOT)}")


if __name__ == "__main__":
    main()
