#!/usr/bin/env python3
"""
build-blog-index.py

Scans the posts/ folder for blog post HTML files and regenerates
assets/js/blog-index.js, which blog.html reads to build its post list
and category filters.

Run this from the site root (the folder this script lives in) every
time you add, edit, or remove a post:

    python3 build-blog-index.py

Each post file (a copy of posts/post template.html) must have, in its
<head>:

    <meta name="post-date" content="YYYY-MM-DD">
    <meta name="post-tags" content="Tag One, Tag Two">

Its display title is taken automatically from the first <h1> inside
<div id="main">, so there's nothing else to fill in.

Posts are listed newest first. posts/post template.html itself is
always skipped, so leaving the template in the posts/ folder is safe.
"""

import json
import sys
from html.parser import HTMLParser
from pathlib import Path

SITE_ROOT = Path(__file__).resolve().parent
POSTS_DIR = SITE_ROOT / "posts"
OUTPUT_FILE = SITE_ROOT / "assets" / "js" / "blog-index.js"
TEMPLATE_NAME = "post template.html"


class PostParser(HTMLParser):
    """Pulls post-date / post-tags meta tags and the first <h1> inside #main."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.date = None
        self.tags = []
        self.title = None
        self._main_depth = None
        self._div_depth = 0
        self._in_title_h1 = False
        self._h1_chunks = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)

        if tag == "meta":
            name = attrs.get("name", "")
            if name == "post-date":
                self.date = (attrs.get("content") or "").strip()
            elif name == "post-tags":
                raw = attrs.get("content") or ""
                self.tags = [t.strip() for t in raw.split(",") if t.strip()]

        if tag == "div":
            self._div_depth += 1
            if attrs.get("id") == "main" and self._main_depth is None:
                self._main_depth = self._div_depth

        if tag == "h1" and self.title is None and self._main_depth is not None:
            self._in_title_h1 = True
            self._h1_chunks = []

    def handle_endtag(self, tag):
        if tag == "div":
            if self._main_depth == self._div_depth:
                self._main_depth = None
            self._div_depth = max(0, self._div_depth - 1)

        if tag == "h1" and self._in_title_h1:
            self._in_title_h1 = False
            self.title = "".join(self._h1_chunks).strip()

    def handle_data(self, data):
        if self._in_title_h1:
            self._h1_chunks.append(data)


def main():
    if not POSTS_DIR.is_dir():
        print(f"No posts/ folder found at {POSTS_DIR}", file=sys.stderr)
        sys.exit(1)

    posts = []
    problems = []

    for path in sorted(POSTS_DIR.glob("*.html")):
        if path.name == TEMPLATE_NAME:
            continue

        parser = PostParser()
        parser.feed(path.read_text(encoding="utf-8"))

        missing = []
        if not parser.date or parser.date.upper() == "YYYY-MM-DD":
            missing.append('<meta name="post-date" content="YYYY-MM-DD"> (filled in with a real date)')
        if not parser.title:
            missing.append('an <h1> title inside <div id="main">')

        if missing:
            problems.append(f"  - posts/{path.name}: missing " + "; ".join(missing))
            continue

        posts.append({
            "file": f"posts/{path.name}",
            "title": parser.title,
            "date": parser.date,
            "tags": parser.tags,
        })

    # Newest first; alphabetical by title as a tiebreaker.
    posts.sort(key=lambda p: (p["date"], p["title"]), reverse=True)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_FILE.open("w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build-blog-index.py — do not edit by hand.\n")
        f.write("// Run `python3 build-blog-index.py` from the site root after adding, editing, or removing a post.\n")
        f.write("window.BLOG_POSTS = ")
        json.dump(posts, f, indent=2, ensure_ascii=False)
        f.write(";\n")

    print(f"Wrote {len(posts)} post(s) to {OUTPUT_FILE.relative_to(SITE_ROOT)}")

    if problems:
        print("\nSkipped file(s) with missing/placeholder metadata:")
        for p in problems:
            print(p)


if __name__ == "__main__":
    main()
